import { ForceConcept } from "./types";

export const FORCE_CONCEPTS: ForceConcept[] = [
  {
    id: "the-force",
    name: "The Force",
    category: "Phenomenon",
    summary:
      "An energy field generated by all living things. It surrounds, penetrates, and binds the galaxy together. Light and Dark are two aspects of the same Force; balance is the natural state.",
    details:
      "Midi-chlorians — microscopic symbionts inside living cells — communicate the will of the Force to sentient beings. Force-sensitivity is heritable but also random. The Force has two great currents: the Living Force (immediate, sensory) and the Cosmic Force (eternal, prophetic). Qui-Gon Jinn discovered how to retain consciousness within the Cosmic Force after death — the secret of becoming a Force ghost.",
    relatedFactions: ["jedi-order", "sith-order", "nightsisters"],
    relatedCharacters: ["yoda", "anakin-skywalker", "luke-skywalker"],
  },
  {
    id: "jedi-philosophy",
    name: "Jedi Philosophy",
    category: "Philosophy",
    summary:
      "Service. Detachment. Compassion without possession. The Jedi Code: 'There is no emotion, there is peace.' Defense before aggression. Knowledge over passion.",
    details:
      "The Jedi reject attachment because attachment leads to fear, fear leads to anger, anger leads to hate, hate leads to suffering. Critics — including Qui-Gon, Ahsoka, Luke, and later Rey — argue the dogmatic Jedi Code makes love into a sin, and that the Order's compassion ossified into hierarchy. The 'Living Force' tradition (Qui-Gon) emphasizes present-moment intuition; the dominant late-Republic Order favored prophecy and detachment, contributing to its blindness.",
    relatedFactions: ["jedi-order"],
    relatedCharacters: ["yoda", "qui-gon-jinn", "mace-windu", "luke-skywalker"],
  },
  {
    id: "sith-philosophy",
    name: "Sith Philosophy",
    category: "Philosophy",
    summary:
      "Passion is power. The strong rule. Domination is freedom. The Sith Code begins: 'Peace is a lie; there is only passion.' The Rule of Two ensures evolution through betrayal.",
    details:
      "The Sith doctrine elevates emotion as fuel — fear, hate, ambition, lust for power. Bane's Rule of Two: one master to embody power, one apprentice to crave it; the apprentice eventually kills the master, ensuring the Order is always led by the strongest. The dark side is corrosive: bodies decay, minds fracture (see Sidious). Yet the dark side also tempts with the promise of preserving life (Plagueis), control over death, and immortality.",
    relatedFactions: ["sith-order", "sith-eternal"],
    relatedCharacters: ["sheev-palpatine", "darth-bane", "darth-plagueis", "darth-vader"],
  },
  {
    id: "gray-jedi",
    name: "Gray Jedi / Balance",
    category: "Philosophy",
    summary:
      "A Force-user who walks between the Jedi Code and the Sith Code. Uses both light and dark, claims no allegiance to either order.",
    details:
      "Largely a Legends concept (Qui-Gon was sometimes called gray; Jolee Bindo in KOTOR is the archetype). In canon, Ahsoka Tano post-Order 66 embodies the spirit: a Force-user who has left the Jedi Order but still serves the light. Rey, post-Exegol, founds a path closer to balance than to either traditional order.",
    relatedFactions: [],
    relatedCharacters: ["qui-gon-jinn", "ahsoka-tano", "rey-skywalker"],
  },
  {
    id: "balance",
    name: "Balance of the Force",
    category: "Prophecy",
    summary:
      "The prophecy of the Chosen One: 'One born of the Force will bring balance.' Anakin fulfills it — twice, in tragedy and redemption.",
    details:
      "Multiple interpretations: (1) balance means destruction of the Sith (since dark-side imbalance corrupts the Force); (2) balance means equilibrium between light and dark; (3) balance means destruction of dogmatic orders on both sides. The Mortis arc explicitly depicts the Father (balance), Son (dark), and Daughter (light). Anakin's death ends the Sith line and Sidious; Luke's choice in RotJ embodies non-violence.",
    relatedFactions: [],
    relatedCharacters: ["anakin-skywalker", "luke-skywalker", "rey-skywalker"],
  },
  {
    id: "mortis-gods",
    name: "Mortis Gods",
    category: "Entity",
    summary:
      "Three powerful Force entities — Father (balance), Son (dark), Daughter (light) — encountered by Anakin, Obi-Wan, and Ahsoka in The Clone Wars.",
    details:
      "On Mortis, an extragalactic-style plane in the Force, the trio test the Chosen One. The Father dies maintaining balance; the Son and Daughter destroy each other. Their physical avatars later appear in Ahsoka as statues on the Dagoyan temple. The 'world between worlds' under their temple lets Ezra rescue Ahsoka from Vader's strike.",
    relatedFactions: [],
    relatedCharacters: ["anakin-skywalker", "obi-wan-kenobi", "ahsoka-tano"],
  },
  {
    id: "whills",
    name: "Whills",
    category: "Entity",
    summary:
      "Mysterious cosmic chroniclers. The Force may be 'the Will of the Whills.' Guardians of the Whills serve them on Jedha.",
    details:
      "Lucas's mythology positions the Whills as the highest-level cosmic observers — perhaps even the Force's authors. Chirrut Îmwe (Rogue One) is a Guardian of the Whills, a monastic order on Jedha that venerates the Force as religion. Star Wars novels are framed as 'Journal of the Whills' translations.",
    relatedFactions: ["guardians-of-the-whills"],
    relatedCharacters: ["chirrut-imwe", "baze-malbus"],
  },
  {
    id: "nightsister-magick",
    name: "Nightsister Magick (Ichor)",
    category: "Phenomenon",
    summary:
      "Dathomir's localized dark-side magic. Uses the planet's ichor in spell-form: invisibility, possession, resurrection, transformation.",
    details:
      "Nightsisters are not Sith; their power flows differently. Mother Talzin uses ichor to restore Maul. Merrin (Fallen Order/Survivor) uses Nightsister magick to summon spirit warriors. Morgan Elsbeth (Ahsoka) carries a Nightsister-forged Beskar sword.",
    relatedFactions: ["nightsisters"],
    relatedCharacters: ["mother-talzin", "merrin", "asajj-ventress"],
  },
  {
    id: "ancient-force-cults",
    name: "Ancient Force Cults",
    category: "Cult",
    summary:
      "Pre-Jedi Force traditions: Je'daii, Bendu, Voss Mystics, Acolytes of the Beyond, Lost Tribe of Sith, Aing-Tii.",
    details:
      "Many of these are Legends. The Bendu (Rebels) describes himself as 'the One in the middle' — embodiment of balance. The Voss Mystics receive visions and reject both Jedi and Sith. The Lost Tribe of Sith (Fate of the Jedi) survived on Kesh for millennia.",
    relatedFactions: [],
    relatedCharacters: [],
  },
  {
    id: "kyber-crystals",
    name: "Kyber Crystals",
    category: "Artifact",
    summary:
      "Force-attuned crystals that power lightsabers. Naturally clear; their color comes from the wielder. Bled by Sith torture.",
    details:
      "Kyber sings to the Force-sensitive. Major sources: Ilum (Empire-strip-mined for Death Star superlaser), Christophsis, Jedha, Dantooine, Mustafar. Sith 'bleed' a stolen kyber — pouring pain into it until it turns red. Ahsoka 'purified' bled kybers to forge her white sabers. Massive kyber crystals power the Death Stars and Starkiller Base.",
    relatedFactions: ["jedi-order", "sith-order"],
    relatedCharacters: ["ahsoka-tano", "luke-skywalker", "wilhuff-tarkin"],
  },
  {
    id: "force-vergences",
    name: "Force Vergences",
    category: "Phenomenon",
    summary:
      "Locations where the Force concentrates intensely. Often dangerous. The cave on Dagobah, Mortis, the Sith Temple on Coruscant, the Lothal Temple, Exegol.",
    details:
      "Vergences amplify visions and Force ability. A vergence around a person (the term used about Anakin) suggests they themselves channel the Force unusually densely. The pilgrim sites for both Jedi (Ahch-To) and Sith (Moraband, Korriban, Exegol) are vergences.",
    relatedFactions: [],
    relatedCharacters: [],
  },
  {
    id: "dark-side-corruption",
    name: "Dark-Side Corruption",
    category: "Phenomenon",
    summary:
      "Repeated dark-side use damages body, mind, and the Force's ability to flow. Sidious's face decays; Vader's body is destroyed; Bane is scarred by his own holocron.",
    details:
      "Corruption manifests physically (yellow Sith eyes, skin necrosis, voice changes) and spiritually (loss of empathy, paranoia). The dark side is faster, easier, more seductive — and ultimately self-destructive. Vader survives only inside life-support; Sidious lives in a wrecked clone body on Exegol.",
    relatedFactions: ["sith-order"],
    relatedCharacters: ["sheev-palpatine", "darth-vader", "darth-maul"],
  },
  {
    id: "the-dyad",
    name: "Dyad in the Force",
    category: "Phenomenon",
    summary:
      "Two Force-users so connected they form a single front in the Force. Once-in-a-generation. Rey and Ben Solo are the canonical dyad.",
    details:
      "A dyad transcends master-apprentice or master-pupil. The two share life force, vision, location, and even physical objects across distance. Palpatine craved their power as a vessel for himself. Rey channels Ben's living energy back to him to heal a fatal wound; he then transfers his life into her at Exegol.",
    relatedFactions: ["sith-eternal"],
    relatedCharacters: ["rey-skywalker", "ben-solo", "sheev-palpatine"],
  },
  {
    id: "prophecy-systems",
    name: "Prophecy Systems",
    category: "Prophecy",
    summary:
      "Multiple Force prophecies operate in the saga: Chosen One, Sith'ari, the Mortis prophecies, Voss visions, Nightsister readings.",
    details:
      "The Sith'ari (Legends) was a Sith messianic prophecy: a perfect being who would destroy the Sith, then make them stronger than ever. Both Bane and Palpatine claimed the title. The Chosen One brings balance. Voss visions are often opaque. Most prophecies are self-fulfilling traps when interpreted with attachment.",
    relatedFactions: [],
    relatedCharacters: ["anakin-skywalker", "rey-skywalker"],
  },
  {
    id: "world-between-worlds",
    name: "World Between Worlds",
    category: "Phenomenon",
    summary:
      "A liminal Force plane connecting all moments in time and space. Accessible from key vergences (Lothal temple).",
    details:
      "Ezra Bridger uses it to rescue Ahsoka from her duel with Vader. Palpatine attempts to enter it but is blocked. Time-travel implications are intentionally constrained — past events cannot be undone (Kanan stays dead), but specific moments can be rerouted.",
    relatedFactions: [],
    relatedCharacters: ["ezra-bridger", "ahsoka-tano"],
  },
  {
    id: "force-ghosts",
    name: "Force Ghosts (Netherworld Manifestation)",
    category: "Phenomenon",
    summary:
      "Light-side technique discovered by the Force priestesses and shared with Qui-Gon Jinn: retain consciousness after death.",
    details:
      "Yoda, Obi-Wan, Anakin, Luke, Leia, Qui-Gon, and Ahsoka have all manifested as Force ghosts. Requires letting go of self. Sith historically could not; some Sith spirits linger as wraiths (Marka Ragnos, Exar Kun — Legends) but these are bound to physical places, not free as Jedi ghosts.",
    relatedFactions: ["jedi-order"],
    relatedCharacters: ["yoda", "obi-wan-kenobi", "anakin-skywalker", "luke-skywalker"],
  },
];

export function findForceConcept(id: string): ForceConcept | undefined {
  return FORCE_CONCEPTS.find((f) => f.id === id);
}
